### ISSUE TITLE
how do you add jasmine and protractor syntax code highlighting in VS Code?

### ISSUE THREAD

**Issue by sammok83** [SAP-samples/teched2019-uiveri5#1]
Tutorial URL: https://developers.sap.com/tutorials/cp-cicd-systemtest-recorder.html

Hi,
Can I please know how do you add jasmine and protractor syntax code highlighting in VS Code?

**Comment by maximnaidenov** [comment]
Hi,
sorry but I have no idea, please check VSCode or Protractor documentation.
